---
title: "Dataset Summary"
author: "James Farrell"
date: "30/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages ----
library(tidyverse)
library(lubridate)
library(finalfit)

# Load custom functions ----
source(here::here("analysis", "00_utility_functions.R"))

# Load patient IDs
data_id = read_rds(here::here("output", "data", "data_id.rds"))

```


```{r load_datasets}

# Data Files ----
files_testing = list.files(path = here::here("output", "data_weekly"),
                           pattern = "input_covid_tests_negative_20\\d{2}-\\d{2}-\\d{2}.csv.gz")

# Read in testing data ----
data_testing = here::here("output", "data_weekly", files_testing) %>%
  map(function(file){
    file %>% 
      read_csv(col_types = read_column_type(.)) %>% 
      as_tibble()
  })

print(data_testing[[1]], n = 50)
print(data_testing[[2]], n = 50)
print(data_testing[[3]], n = 50)

```

```{r}

# Extract diagnostics data  ----
diagnostics_testing = data_testing %>%
  map(function(data){
    n_row = nrow(data)
    n_row_bad_id = data %>%
      filter(!patient_id %in% data_id$patient_id) %>%
      nrow()
    n_col = ncol(data)
    n_col_empty = data %>%
      select_if(~(all(is.na(.)))) %>%
      ncol()
    n_empty_col_1 = data %>% pull(covid_negative_test_date_1) %>% is.na() %>% sum()
    tibble(n_row, n_row_bad_id, n_col, n_col_empty, n_empty_col_1)
  }) %>%
  bind_rows() %>%
  mutate(file = files_testing) %>%
  relocate(file)

# Filter out bad patient IDs, pivot longer ----
data_testing = data_testing %>%
  map(function(data){
    data %>%
      filter(patient_id %in% data_id$patient_id) %>%
      select(-ends_with("_count")) %>%
      pivot_longer(
        cols = -patient_id,
        names_to = c("result", "index"),
        names_pattern = "covid_(.*)_test_date_(\\d+)",
        values_to = "test_date",
        values_drop_na = TRUE
      ) %>%
      select(-index)
  }) %>%
  bind_rows() %>%
  arrange(patient_id, test_date, result) %>%
  distinct(patient_id, test_date, result)

print(data_testing, n = 150)


```

